// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockitfUser creates a new instance of mockitfUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockitfUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockitfUser {
	mock := &mockitfUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockitfUser is an autogenerated mock type for the itfUser type
type mockitfUser struct {
	mock.Mock
}

type mockitfUser_Expecter struct {
	mock *mock.Mock
}

func (_m *mockitfUser) EXPECT() *mockitfUser_Expecter {
	return &mockitfUser_Expecter{mock: &_m.Mock}
}

// GetAuthKey provides a mock function for the type mockitfUser
func (_mock *mockitfUser) GetAuthKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuthKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockitfUser_GetAuthKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthKey'
type mockitfUser_GetAuthKey_Call struct {
	*mock.Call
}

// GetAuthKey is a helper method to define mock.On call
func (_e *mockitfUser_Expecter) GetAuthKey() *mockitfUser_GetAuthKey_Call {
	return &mockitfUser_GetAuthKey_Call{Call: _e.mock.On("GetAuthKey")}
}

func (_c *mockitfUser_GetAuthKey_Call) Run(run func()) *mockitfUser_GetAuthKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockitfUser_GetAuthKey_Call) Return(s string) *mockitfUser_GetAuthKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockitfUser_GetAuthKey_Call) RunAndReturn(run func() string) *mockitfUser_GetAuthKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogin provides a mock function for the type mockitfUser
func (_mock *mockitfUser) GetLogin() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogin")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockitfUser_GetLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogin'
type mockitfUser_GetLogin_Call struct {
	*mock.Call
}

// GetLogin is a helper method to define mock.On call
func (_e *mockitfUser_Expecter) GetLogin() *mockitfUser_GetLogin_Call {
	return &mockitfUser_GetLogin_Call{Call: _e.mock.On("GetLogin")}
}

func (_c *mockitfUser_GetLogin_Call) Run(run func()) *mockitfUser_GetLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockitfUser_GetLogin_Call) Return(s string) *mockitfUser_GetLogin_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockitfUser_GetLogin_Call) RunAndReturn(run func() string) *mockitfUser_GetLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// AddNewOrder provides a mock function for the type MockStorage
func (_mock *MockStorage) AddNewOrder(ctx context.Context, orderNum string, userNm string) (string, error) {
	ret := _mock.Called(ctx, orderNum, userNm)

	if len(ret) == 0 {
		panic("no return value specified for AddNewOrder")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, orderNum, userNm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, orderNum, userNm)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, orderNum, userNm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_AddNewOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewOrder'
type MockStorage_AddNewOrder_Call struct {
	*mock.Call
}

// AddNewOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
//   - userNm string
func (_e *MockStorage_Expecter) AddNewOrder(ctx any, orderNum any, userNm any) *MockStorage_AddNewOrder_Call {
	return &MockStorage_AddNewOrder_Call{Call: _e.mock.On("AddNewOrder", ctx, orderNum, userNm)}
}

func (_c *MockStorage_AddNewOrder_Call) Run(run func(ctx context.Context, orderNum string, userNm string)) *MockStorage_AddNewOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorage_AddNewOrder_Call) Return(username string, err error) *MockStorage_AddNewOrder_Call {
	_c.Call.Return(username, err)
	return _c
}

func (_c *MockStorage_AddNewOrder_Call) RunAndReturn(run func(ctx context.Context, orderNum string, userNm string) (string, error)) *MockStorage_AddNewOrder_Call {
	_c.Call.Return(run)
	return _c
}

// AddNewWithdraw provides a mock function for the type MockStorage
func (_mock *MockStorage) AddNewWithdraw(ctx context.Context, orderNum string, userNm string, sum float64) error {
	ret := _mock.Called(ctx, orderNum, userNm, sum)

	if len(ret) == 0 {
		panic("no return value specified for AddNewWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, float64) error); ok {
		r0 = returnFunc(ctx, orderNum, userNm, sum)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_AddNewWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewWithdraw'
type MockStorage_AddNewWithdraw_Call struct {
	*mock.Call
}

// AddNewWithdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
//   - userNm string
//   - sum float64
func (_e *MockStorage_Expecter) AddNewWithdraw(ctx any, orderNum any, userNm any, sum any) *MockStorage_AddNewWithdraw_Call {
	return &MockStorage_AddNewWithdraw_Call{Call: _e.mock.On("AddNewWithdraw", ctx, orderNum, userNm, sum)}
}

func (_c *MockStorage_AddNewWithdraw_Call) Run(run func(ctx context.Context, orderNum string, userNm string, sum float64)) *MockStorage_AddNewWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_AddNewWithdraw_Call) Return(err error) *MockStorage_AddNewWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_AddNewWithdraw_Call) RunAndReturn(run func(ctx context.Context, orderNum string, userNm string, sum float64) error) *MockStorage_AddNewWithdraw_Call {
	_c.Call.Return(run)
	return _c
}

// AddUser provides a mock function for the type MockStorage
func (_mock *MockStorage) AddUser(ctx context.Context, user itfUser) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AddUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, itfUser) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_AddUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUser'
type MockStorage_AddUser_Call struct {
	*mock.Call
}

// AddUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user itfUser
func (_e *MockStorage_Expecter) AddUser(ctx any, user any) *MockStorage_AddUser_Call {
	return &MockStorage_AddUser_Call{Call: _e.mock.On("AddUser", ctx, user)}
}

func (_c *MockStorage_AddUser_Call) Run(run func(ctx context.Context, user itfUser)) *MockStorage_AddUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 itfUser
		if args[1] != nil {
			arg1 = args[1].(itfUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_AddUser_Call) Return(err error) *MockStorage_AddUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_AddUser_Call) RunAndReturn(run func(ctx context.Context, user itfUser) error) *MockStorage_AddUser_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockStorage
func (_mock *MockStorage) Close() {
	_mock.Called()
	return
}

// MockStorage_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorage_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Close() *MockStorage_Close_Call {
	return &MockStorage_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorage_Close_Call) Run(run func()) *MockStorage_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Close_Call) Return() *MockStorage_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_Close_Call) RunAndReturn(run func()) *MockStorage_Close_Call {
	_c.Run(run)
	return _c
}

// CreateSession provides a mock function for the type MockStorage
func (_mock *MockStorage) CreateSession(ctx context.Context, user itfUser) (string, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, itfUser) (string, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, itfUser) string); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, itfUser) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockStorage_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - user itfUser
func (_e *MockStorage_Expecter) CreateSession(ctx any, user any) *MockStorage_CreateSession_Call {
	return &MockStorage_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, user)}
}

func (_c *MockStorage_CreateSession_Call) Run(run func(ctx context.Context, user itfUser)) *MockStorage_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 itfUser
		if args[1] != nil {
			arg1 = args[1].(itfUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_CreateSession_Call) Return(session string, err error) *MockStorage_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockStorage_CreateSession_Call) RunAndReturn(run func(ctx context.Context, user itfUser) (string, error)) *MockStorage_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdesList provides a mock function for the type MockStorage
func (_mock *MockStorage) GetOrdesList(ctx context.Context, userNm string, lim_stt int, count int) ([]OrderData, error) {
	ret := _mock.Called(ctx, userNm, lim_stt, count)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdesList")
	}

	var r0 []OrderData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]OrderData, error)); ok {
		return returnFunc(ctx, userNm, lim_stt, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []OrderData); ok {
		r0 = returnFunc(ctx, userNm, lim_stt, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]OrderData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, userNm, lim_stt, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetOrdesList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdesList'
type MockStorage_GetOrdesList_Call struct {
	*mock.Call
}

// GetOrdesList is a helper method to define mock.On call
//   - ctx context.Context
//   - userNm string
//   - lim_stt int
//   - count int
func (_e *MockStorage_Expecter) GetOrdesList(ctx any, userNm any, lim_stt any, count any) *MockStorage_GetOrdesList_Call {
	return &MockStorage_GetOrdesList_Call{Call: _e.mock.On("GetOrdesList", ctx, userNm, lim_stt, count)}
}

func (_c *MockStorage_GetOrdesList_Call) Run(run func(ctx context.Context, userNm string, lim_stt int, count int)) *MockStorage_GetOrdesList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_GetOrdesList_Call) Return(data []OrderData, err error) *MockStorage_GetOrdesList_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockStorage_GetOrdesList_Call) RunAndReturn(run func(ctx context.Context, userNm string, lim_stt int, count int) ([]OrderData, error)) *MockStorage_GetOrdesList_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBySession provides a mock function for the type MockStorage
func (_mock *MockStorage) GetUserBySession(ctx context.Context, session string) (UserData, error) {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBySession")
	}

	var r0 UserData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (UserData, error)); ok {
		return returnFunc(ctx, session)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) UserData); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Get(0).(UserData)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetUserBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBySession'
type MockStorage_GetUserBySession_Call struct {
	*mock.Call
}

// GetUserBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - session string
func (_e *MockStorage_Expecter) GetUserBySession(ctx any, session any) *MockStorage_GetUserBySession_Call {
	return &MockStorage_GetUserBySession_Call{Call: _e.mock.On("GetUserBySession", ctx, session)}
}

func (_c *MockStorage_GetUserBySession_Call) Run(run func(ctx context.Context, session string)) *MockStorage_GetUserBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetUserBySession_Call) Return(data UserData, err error) *MockStorage_GetUserBySession_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockStorage_GetUserBySession_Call) RunAndReturn(run func(ctx context.Context, session string) (UserData, error)) *MockStorage_GetUserBySession_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawalsList provides a mock function for the type MockStorage
func (_mock *MockStorage) GetWithdrawalsList(ctx context.Context, userNm string) ([]WithdrawData, error) {
	ret := _mock.Called(ctx, userNm)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsList")
	}

	var r0 []WithdrawData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]WithdrawData, error)); ok {
		return returnFunc(ctx, userNm)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []WithdrawData); ok {
		r0 = returnFunc(ctx, userNm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]WithdrawData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userNm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetWithdrawalsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalsList'
type MockStorage_GetWithdrawalsList_Call struct {
	*mock.Call
}

// GetWithdrawalsList is a helper method to define mock.On call
//   - ctx context.Context
//   - userNm string
func (_e *MockStorage_Expecter) GetWithdrawalsList(ctx any, userNm any) *MockStorage_GetWithdrawalsList_Call {
	return &MockStorage_GetWithdrawalsList_Call{Call: _e.mock.On("GetWithdrawalsList", ctx, userNm)}
}

func (_c *MockStorage_GetWithdrawalsList_Call) Run(run func(ctx context.Context, userNm string)) *MockStorage_GetWithdrawalsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetWithdrawalsList_Call) Return(data []WithdrawData, err error) *MockStorage_GetWithdrawalsList_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *MockStorage_GetWithdrawalsList_Call) RunAndReturn(run func(ctx context.Context, userNm string) ([]WithdrawData, error)) *MockStorage_GetWithdrawalsList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdOrderData provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdOrderData(ctx context.Context, orderNum string, orserStt int, accrual float64) error {
	ret := _mock.Called(ctx, orderNum, orserStt, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdOrderData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, float64) error); ok {
		r0 = returnFunc(ctx, orderNum, orserStt, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_UpdOrderData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdOrderData'
type MockStorage_UpdOrderData_Call struct {
	*mock.Call
}

// UpdOrderData is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNum string
//   - orserStt int
//   - accrual float64
func (_e *MockStorage_Expecter) UpdOrderData(ctx any, orderNum any, orserStt any, accrual any) *MockStorage_UpdOrderData_Call {
	return &MockStorage_UpdOrderData_Call{Call: _e.mock.On("UpdOrderData", ctx, orderNum, orserStt, accrual)}
}

func (_c *MockStorage_UpdOrderData_Call) Run(run func(ctx context.Context, orderNum string, orserStt int, accrual float64)) *MockStorage_UpdOrderData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorage_UpdOrderData_Call) Return(err error) *MockStorage_UpdOrderData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_UpdOrderData_Call) RunAndReturn(run func(ctx context.Context, orderNum string, orserStt int, accrual float64) error) *MockStorage_UpdOrderData_Call {
	_c.Call.Return(run)
	return _c
}
